<?php
/**
 * @file
 * Editorial dashboard module.
 *
 * Provides integration with editorial base system.
 */

/**
 * Implements hook_menu().
 */
function easyddb_editorial_base_menu() {
  $menu = array();

  $menu['admin/config/edbase'] = array(
    'title' => 'Editorial Base',
    'description' => 'Editorial Base settings',
    'access arguments' => array('administer editorial base'),
    'page callback' => 'easyddb_editorial_base_admin_menu_block_page',
    'page arguments' => array(),
    'file' => 'easyddb_editorial_base.admin.inc',
  );

  $menu['admin/config/edbase/content'] = array(
    'title' => 'Content types',
    'description' => 'Node bundles that are a part of editorial base system',
    'access arguments' => array('administer editorial base'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('easyddb_editorial_base_admin_content_types'),
    'file' => 'easyddb_editorial_base.admin.inc',
  );

  return $menu;
}

/**
 * Implements hook_permission().
 */
function easyddb_editorial_base_permission() {
  $perm = array();

  $perm['administer editorial base'] = array(
    'title' => 'Administer editorial base',
    'description' => 'Change various editorial base settings'
  );

  $perm['view editorialbase panels terms'] = array(
    'title' => 'View Panel for terms',
  );

  $perm['use editorialbase panels terms'] = array(
    'title' => 'Use the Panels In-Place Editor for terms',
  );

  return $perm;
}

/**
 *  Implements hook_secure_permissions().
 */
function easyddb_editorial_base_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
      'view editorialbase panels terms',
    ),
    'authenticated user' => array(
      'view editorialbase panels terms',
    ),
    'administrators' => array(
      'view editorialbase panels terms',
    ),
    'editor' => array(
      'view editorialbase panels terms',
      'use editorialbase panels terms',
    ),
    'guest blogger' => array(
      'view editorialbase panels terms',
    ),
    'local administrator' => array(
      'create editorial_base content',
      'edit any editorial_base content',
      'edit own editorial_base content',
      'delete any editorial_base content',
      'delete own editorial_base content',
      'administer editorial base',
      'view editorialbase panels terms',
      'use editorialbase panels terms',
    ),
    'local editor' => array(
      'view editorialbase panels terms',
    ),
    'provider' => array(
      'view editorialbase panels terms',
    ),
    'staff' => array(
      'view editorialbase panels terms',
    ),
  );
  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/*
 * Implement hook_form_FORM_ID_alter().
 *
 * Alter taxonomy term (section) form.
 */
function easyddb_editorial_base_form_taxonomy_form_term_alter(&$form, &$form_state) {
  if (!isset($form['#bundle']) || $form['#bundle'] != 'editorial_base') {
    return;
  }

  $form['section_tabs'] = array(
    '#type' => 'vertical_tabs'
  );

  $tabs = module_invoke_all('section_tabs');

  if (is_array($tabs)) {
    $form += $tabs;
  }

  $form['relations']['#group'] = 'section_tabs';
}
