<?php
/**
 * @file
 * Provides functionality of creating menu entry for term.
 */

/**
 *  Implements hook_form_FORM_ID_alter().
 */
function easyddb_editorial_base_term_menu_form_taxonomy_form_term_alter(&$form, &$form_state) {
  // Generate a list of possible parents (not including this link or descendants).
  $type = 'eb_term';
  $link = array(
    'link_title' => '',
    'mlid' => 0,
    'plid' => 0,
    'menu_name' => 'main-menu',
    'weight' => 0,
    'options' => array(),
    'module' => 'menu',
    'expanded' => 0,
    'hidden' => 0,
    'has_children' => 0,
    'customized' => 0,
    'parent_depth_limit' => 8,
  );
  if ($form['#term']['tid'] != null) {
    // Check if term already have menu.
    $mlid = _easyddb_editorial_base_menu_exist($form['#term']['tid']);
    if ($mlid) {
      $link = menu_link_load($mlid[0]);
    }
  }

  // menu_parent_options() is goofy and can actually handle either a menu link
  // or a node type both as second argument. Pick based on whether there is
  // a link already (menu_node_prepare() sets mlid default to 0).
  $options = menu_parent_options(menu_get_menus(), $link['mlid'], $type);
  // If no possible parent menu items were found, there is nothing to display.
  if (empty($options)) {
    return;
  }

  $form['editorial_base'] = array(
    '#type' => 'fieldset',
    '#title' => t('Menu settings'),
    '#access' => user_access('administer menu'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#group' => 'additional_settings',
    '#attached' => array(
      'js' => array(drupal_get_path('module', 'menu') . '/menu.js'),
    ),
    '#tree' => TRUE,
    '#weight' => -2,
    '#attributes' => array('class' => array('menu-link-form')),
  );
  $form['editorial_base']['enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Provide a menu link'),
    '#default_value' => !empty($link['mlid']),
  );
  $form['editorial_base']['link'] = array(
    '#type' => 'container',
    '#parents' => array('menu'),
    '#states' => array(
      'invisible' => array(
        'input[name="editorial_base[enabled]"]' => array('checked' => FALSE),
      ),
    ),
  );

  // Populate the element with the link data.
  foreach (array('mlid', 'module', 'hidden', 'has_children', 'customized', 'options', 'expanded', 'hidden') as $key) {
    $form['menu']['link'][$key] = array('#type' => 'value', '#value' => $link[$key]);
  }

  $form['editorial_base']['link']['link_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Menu link title'),
    '#default_value' => $link['link_title'],
  );

  $form['editorial_base']['link']['description'] = array(
    '#type' => 'textarea',
    '#title' => t('Description'),
    '#default_value' => isset($link['options']['attributes']['title']) ? $link['options']['attributes']['title'] : '',
    '#rows' => 1,
    '#description' => t('Shown when hovering over the menu link.'),
  );

  $default = ($link['mlid'] ? $link['menu_name'] . ':' . $link['plid'] : variable_get('menu_parent_' . $type, 'main-menu:0'));
  // If the current parent menu item is not present in options, use the first
  // available option as default value.
  // @todo User should not be allowed to access menu link settings in such a
  // case.
  if (!isset($options[$default])) {
    $array = array_keys($options);
    $default = reset($array);
  }
  $form['editorial_base']['link']['parent'] = array(
    '#type' => 'select',
    '#title' => t('Parent item'),
    '#default_value' => $default,
    '#options' => $options,
    '#attributes' => array('class' => array('menu-parent-select')),
  );
  $form['editorial_base']['link']['weight'] = array(
    '#type' => 'weight',
    '#title' => t('Weight'),
    '#delta' => 50,
    '#default_value' => $link['weight'],
    '#description' => t('Menu links with smaller weights are displayed before links with larger weights.'),
  );
  $form['#validate'][] = 'easyddb_editorial_base_term_validate';
  $form['#submit'][] = 'easyddb_editorial_base_term_submit';
}

/**
 * Callback function for term form enabled.
 */
function easyddb_editorial_base_term_validate($form, &$form_state) {
  if ($form_state['values']['editorial_base']['enabled'] == 1) {
    $menu_parameters = array(
      'link_title' => 'Menu link title',
      'parent' => 'Parent item',
    );
    $menu_vals = $form_state['values']['menu'];
    foreach ($menu_parameters as $parameter => $parameter_name) {
      if (empty($menu_vals[$parameter])) {
        form_set_error($parameter, t($parameter_name . ' not set.'));
      }
    }
  }
}

/**
 * Callback function for term form save.
 */
function easyddb_editorial_base_term_submit($form, $form_state) {
  $tid = $form_state['term']->tid;

  if ($form_state['values']['editorial_base']['enabled'] == 0) {
    $mlid = _easyddb_editorial_base_menu_exist($tid);
    if ($mlid) {
      _easyddb_editorial_base_remove_term_menu($tid, $mlid[0]);
      drupal_set_message(t('Menu for @term was deleted.', array('@term' => $form_state['term']->name)), 'status');
    }
  }

  if ($form_state['values']['editorial_base']['enabled'] == 1) {
    // If menu exist skip creation.
    if (_easyddb_editorial_base_menu_exist($tid)) {
      return FALSE;
    }

    if (empty($form_state['values']['path']['source'])) {
      $link_path = 'taxonomy/term/' . $tid;
    }
    else {
      $link_path = $form_state['values']['path']['source'];
    }

    $vals = $form_state['values']['menu'];
    $menu_link = array(
      'menu_name' => strstr($vals['parent'], ":" , TRUE),
      'link_path' => $link_path,
      'link_title' => $vals['link_title'],
      'weight' => $vals['weight'],
      'mlid' => NULL,
    );
    $mlid = menu_link_save($menu_link);
    menu_cache_clear_all();

    if (!$mlid) {
      drupal_set_message(t('Menu wasn\'t created'), 'error');
    }

    _easyddb_editorial_base_create_term_menu($tid, $mlid);
  }
}

/**
 * Check term already have menu.
 *
 * @param $tid term id.
 * @return mixed false if no menu, array with mlid if exist.
 */
function _easyddb_editorial_base_menu_exist($tid) {
  $mlid = db_select('eb_term_menu', 'etm')
    ->fields('etm', array('mlid'))
    ->condition('tid', $tid)
    ->execute()
    ->fetchCol();

  return $mlid;
}

/**
 * Write to database to which term menu is related.
 *
 * @param $tid term id.
 * @param $mlid menu list id.
 */
function _easyddb_editorial_base_create_term_menu($tid, $mlid) {
  db_insert('eb_term_menu')
    ->fields(array(
      'tid' => $tid,
      'mlid' => $mlid,
    ))
    ->execute();
}

/**
 * Delete term menu from database.
 *
 * @param $tid term id.
 * @param $mlid menu list id.
 */
function _easyddb_editorial_base_remove_term_menu($tid, $mlid) {
  menu_link_delete($mlid);
  db_delete('eb_term_menu')
    ->condition('tid', $tid)
    ->execute();
}
