<?php
/**
 * @file
 * easyddb_editorial_base_custom_css.module
 */

/**
 * Implements hook_page_alter().
 * Add custom css on the term view and related node.
 */
function easyddb_editorial_base_custom_css_page_alter(&$page) {
  $css = '';
  $menu_item = menu_get_active_trail();
  $menu_item = array_reverse($menu_item);

  foreach ($menu_item as $key => $menu) {
    if (isset($menu_item[$key + 1]['router_path'])) {
      if ($menu_item[$key + 1]['router_path'] == 'taxonomy/term/%' && $menu_item[$key + 1] != NULL) {
        $menu_object = menu_get_object('taxonomy_term', '2', $menu_item[$key + 1]['link_path']);
        if ($menu_object->vocabulary_machine_name == 'editorial_base' && !empty($menu_object->field_custom_css)) {
          $css = $menu_object->field_custom_css[LANGUAGE_NONE][0]['value'];
          break;
        }
      }
    }
  }

  $term = menu_get_object('taxonomy_term', 2);
  if ($term && $term->vocabulary_machine_name == 'editorial_base') {
    $css = (!empty($term->field_custom_css)) ? $term->field_custom_css[LANGUAGE_NONE][0]['value'] : $css;
  }
  $node = menu_get_object('node', 1);
  if (isset($node->field_editorial_base) && !empty($node->field_editorial_base)) {
    $tid = $node->field_editorial_base[LANGUAGE_NONE][0]['tid'];
    $term = taxonomy_term_load($tid);
    $css = (isset($term->field_custom_css) && !empty($term->field_custom_css)) ? $term->field_custom_css[LANGUAGE_NONE][0]['value'] : FALSE;
  }
  drupal_add_css($css, array('type' => 'inline'));
}
