<?php
/**
 * @file
 *
 */

/**
 * Implements hook_page_alter().
 * Sets specific header image for taxonomy term page.
 */
function easyddb_editorial_base_header_image_page_alter(&$page) {
  $term = menu_get_object('taxonomy_term', 2);
  if ($term) {
    if ($term->vocabulary_machine_name == 'editorial_base') {
      $lang = field_language('taxonomy_term', $term, 'field_header_image');
      if (isset($term->field_header_image[$lang][0]) && !empty($term->field_header_image[$lang][0])) {
        $image = $term->field_header_image[$lang][0];
        // Set specific background.
        $url = file_create_url($image['uri']);
        if ($url != FALSE) {
          $css = ".topbar-inner {
            background-image: url({$url}) !important;
          }";
          drupal_add_css($css, array('type' => 'inline'));
        }
      }
    }
  }
}

/**
 *  Implements hook_form_FORM_ID_alter().
 */
function easyddb_editorial_base_header_image_form_taxonomy_form_term_alter(&$form, &$form_state, $form_id) {
  // Add header image into tab.
  $form['easyddb_editorial_base']['header_image'] = array(
    '#type' => 'fieldset',
    '#title' => t('Header image'),
    '#group' => 'section_tabs',
  );

  $form['easyddb_editorial_base']['header_image']['field'] = $form['field_header_image'];
  unset($form['field_header_image']);
}
